server:
  port: 8090

spring:
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration


  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: help-service
              uri: http://localhost:8080
              predicates:
                - Path=/help/**
              filters:
                - StripPrefix=1
            - id: register-service
              uri: http://localhost:8081
              predicates:
                - Path=/register/**
              filters:
                - StripPrefix=1

            - id: register-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
